/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentation;

import ValueObjects.*;
import BussinessLogicLayers.BLL.*;
import java.awt.HeadlessException;
import java.io.File;
import javax.swing.table.DefaultTableModel;
import java.util.*;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author Nguy Minh Trong
 */
public final class Scheduled extends javax.swing.JInternalFrame {

    private final JFileChooser fileScheduled;
    private String filename;

    /**
     * Creates new form Scheduled
     */
    public Scheduled() {
        initComponents();
        fileScheduled = new JFileChooser();
        fileScheduled.setCurrentDirectory(new File("C:\\Users\\Nguy Minh Trong\\Desktop"));
        fileScheduled.setFileFilter(new FileNameExtensionFilter("File CSV", "csv"));
        fileScheduled.setMultiSelectionEnabled(true);
        LoadThoiKhoaBieu();
        String malop = cbbMonHoc.getItemAt(1);
        LoadScheduled(malop);
        cbbMonHoc.removeItemAt(0);
    }

    @SuppressWarnings("unchecked")

    public void LoadThoiKhoaBieu() {
        try {
            List<ClassObjects> lst = new ClassBLL().getElement();
            cbbMonHoc.addItem("Bạn hãy chọn môn");
            lst.forEach((lop) -> {
                cbbMonHoc.addItem(lop.getMaLop());
            });
        } catch (Exception ex) {
            ex.getMessage();
        }
    }

    public void LoadScheduled(String malop) {
        List<ScheduledObjects> lst = new ScheduledBLL().getElementByMaLop(malop);
        if (!lst.isEmpty()) {
            DefaultTableModel model = (DefaultTableModel) tblThoiKhoaBieu.getModel();
            model.setRowCount(0);
            String[] columnsName = {"STT", "Mã Môn", "Tên Môn", "Phòng Học"};
            model.setColumnIdentifiers(columnsName);
            int i = 1;
            for (ScheduledObjects sc : lst) {
                Vector row = new Vector();
                String number = Integer.toString(i);
                row.add(number);
                row.add(sc.getMaMon());
                SubjectsObjects su = new SubjectsObjectsBLL().GetElementByID(sc.getMaMon());
                row.add(su.getTenMon());
                row.add(sc.getPhongHoc());
                model.addRow(row);
                i++;
            }
        }
    }

    public void LoadImportFileScheduled(String file) {
        List<ScheduledObjects> lst = new ScheduledBLL().GetElementImportfileCSV(file);
        if (!lst.isEmpty()) {
            DefaultTableModel model = (DefaultTableModel) tblThoiKhoaBieu.getModel();
            model.setRowCount(0);
            String[] columnsName = {"STT", "Mã Môn", "Tên Môn", "Phòng Học"};
            model.setColumnIdentifiers(columnsName);
            int i = 1;
            for (ScheduledObjects sc : lst) {
                Vector row = new Vector();
                String number = Integer.toString(i);
                row.add(number);
                row.add(sc.getMaMon());
                SubjectsObjects su = new SubjectsObjectsBLL().GetElementByID(sc.getMaMon());
                row.add(su.getTenMon());
                row.add(sc.getPhongHoc());
                model.addRow(row);
                i++;
            }
            tblThoiKhoaBieu.setModel(model);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnThoiKhoaBieu = new javax.swing.JPanel();
        btnThoiKhoaBieu = new javax.swing.JButton();
        spThoiKhoaBieu = new javax.swing.JScrollPane();
        tblThoiKhoaBieu = new javax.swing.JTable();
        cbbMonHoc = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();

        setClosable(true);
        setMaximumSize(null);
        setVisible(false);

        pnThoiKhoaBieu.setBorder(javax.swing.BorderFactory.createTitledBorder("Thời Khóa Biểu"));

        btnThoiKhoaBieu.setText("Import Thời Khóa Biểu");
        btnThoiKhoaBieu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThoiKhoaBieuActionPerformed(evt);
            }
        });

        tblThoiKhoaBieu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        spThoiKhoaBieu.setViewportView(tblThoiKhoaBieu);

        cbbMonHoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbbMonHocActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnThoiKhoaBieuLayout = new javax.swing.GroupLayout(pnThoiKhoaBieu);
        pnThoiKhoaBieu.setLayout(pnThoiKhoaBieuLayout);
        pnThoiKhoaBieuLayout.setHorizontalGroup(
            pnThoiKhoaBieuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(spThoiKhoaBieu)
            .addGroup(pnThoiKhoaBieuLayout.createSequentialGroup()
                .addContainerGap(335, Short.MAX_VALUE)
                .addComponent(cbbMonHoc, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnThoiKhoaBieu, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(305, 305, 305))
        );
        pnThoiKhoaBieuLayout.setVerticalGroup(
            pnThoiKhoaBieuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnThoiKhoaBieuLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnThoiKhoaBieuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnThoiKhoaBieu, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
                    .addComponent(cbbMonHoc))
                .addGap(18, 18, 18)
                .addComponent(spThoiKhoaBieu, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(330, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 556, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnThoiKhoaBieu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnThoiKhoaBieu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public static String filename(String str, char sep, char ext) {
        String fullpath = str;
        int dot1 = fullpath.lastIndexOf(ext);
        int sep1 = fullpath.lastIndexOf(sep);
        return fullpath.substring(sep1 + 1, dot1);
    }

    private void btnThoiKhoaBieuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThoiKhoaBieuActionPerformed
        // TODO add your handling code here:
        int returnvalue = fileScheduled.showOpenDialog(this);
        if (returnvalue == JFileChooser.APPROVE_OPTION) {
            File[] files = fileScheduled.getSelectedFiles();
            for (File file : files) {
                try {
                    filename = file.toString();
                    String fi = filename(filename, '\\', ' ');
                    int hocky = Integer.parseInt(filename(filename, 'K', '_'));
                    String namhoc = filename(filename, '_', '.');
                    ClassObjects cl = new ClassObjects();
                    cl.setMaLop(fi);
                    new ClassBLL().Insert(cl);
                    List<ThoiKhoaBieuObjects> lstimportdanhsach = new ThoiKhoaBieuBLL().GetElementImportfileCSV(filename);
                    int size = lstimportdanhsach.size();
                    for(int i = 0; i < size; i++)
                    {
                        ScheduledObjects sc = new ScheduledObjects();
                        sc.setMaLop(fi);
                        sc.setMaMon(lstimportdanhsach.get(i).getMaMon());
                        SubjectsObjects su = new SubjectsObjects();
                        su.setMaMon(lstimportdanhsach.get(i).getMaMon());
                        su.setTenMon(lstimportdanhsach.get(i).getTenMon());
                        sc.setHocky(hocky);
                        sc.setNamHoc(namhoc);
                        sc.setPhongHoc(lstimportdanhsach.get(i).getPhonghoc());
                        new ScheduledBLL().Insert(sc);
                        new SubjectsObjectsBLL().Insert(su);
                    }
                    LoadScheduled(fi);
                    cbbMonHoc.removeAllItems();
                    LoadThoiKhoaBieu();
                    cbbMonHoc.removeItemAt(0);
                    cbbMonHoc.setSelectedItem(fi);
                } catch (Exception ex) {
                    ex.getMessage();
                }
            }
        }
    }//GEN-LAST:event_btnThoiKhoaBieuActionPerformed

    private void cbbMonHocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbbMonHocActionPerformed
        // TODO add your handling code here:
//        filename = cbbMonHoc.getSelectedItem() + ".csv";
//        LoadScheduled(filename);
    }//GEN-LAST:event_cbbMonHocActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnThoiKhoaBieu;
    private javax.swing.JComboBox<String> cbbMonHoc;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel pnThoiKhoaBieu;
    private javax.swing.JScrollPane spThoiKhoaBieu;
    private javax.swing.JTable tblThoiKhoaBieu;
    // End of variables declaration//GEN-END:variables
}
