/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentation;

import BussinessLogicLayers.BLL.*;
import ValueObjects.*;
import java.io.File;
import java.math.BigDecimal;
import java.math.MathContext;
import java.util.*;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Nguy Minh Trong
 */
public class SeePointed extends javax.swing.JInternalFrame {

    private static String filename, username;

    /**
     * Creates new form SeePointed
     *
     * @param user
     */
    public SeePointed(String user) {
        username = user;
        initComponents();
        LoadMonHoc();
    }
    
    public static String filename(String str, char sep, char ext) {
        String fullpath = str;
        int dot1 = fullpath.lastIndexOf(ext);
        int sep1 = fullpath.lastIndexOf(sep);
        return fullpath.substring(sep1 + 1, dot1);
    }
    
    public void Loadlistlopcuasinhvien() {

        try {
            File f = new File("src/DataAccessLayers/Database/XemDiem");
            String[] files = f.list();
            for (String file : files) {
                cbblop.addItem(filename(file, '/', '.'));
            }
        } catch (Exception ex) {
            ex.getMessage();
        }
    }

    public void LoadMonHoc() {
//        String ms = (String)cbblop.getSelectedItem();
//        filename = ms + ".csv";
//        List<ScheduledObjects> lstMonHoc = new ScheduledBLL().getElement(filename);
//        for (ScheduledObjects sc : lstMonHoc) {
//            String monhoc = (String) sc.getTenMon();
//            cbbMonHoc.addItem(monhoc);
//        }
//        List<StudentObjects> lst = new StudentBLL().getElement(filename);
//        int size = lst.size();
//        for (int i = 0; i < size; i++) {
//            if (lst.get(i).getMSSV().equals(username)) {
//                txtMSSV.setText(lst.get(i).getMSSV());
//                txtHoTen.setText(lst.get(i).getHoten());
//                break;
//            }
//        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblDiemSV = new javax.swing.JLabel();
        lblHoTen = new javax.swing.JLabel();
        txtHoTen = new javax.swing.JTextField();
        lblMSSV = new javax.swing.JLabel();
        txtMSSV = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        lblMonHoc = new javax.swing.JLabel();
        cbbMonHoc = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblBangDiem = new javax.swing.JTable();
        btnXemDiem = new javax.swing.JButton();
        cbblop = new javax.swing.JComboBox<>();

        setClosable(true);

        lblDiemSV.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        lblDiemSV.setForeground(new java.awt.Color(255, 0, 0));
        lblDiemSV.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDiemSV.setText("ĐIỂM CỦA SINH VIÊN");

        lblHoTen.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblHoTen.setText("Họ Tên Sinh Viên:");

        txtHoTen.setEditable(false);
        txtHoTen.setBackground(new java.awt.Color(204, 204, 204));

        lblMSSV.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblMSSV.setText("Mã Số Sinh Viên:");

        txtMSSV.setEditable(false);
        txtMSSV.setBackground(new java.awt.Color(204, 204, 204));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel1.setText("Lớp:");

        lblMonHoc.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblMonHoc.setText("Môn Học:");

        cbbMonHoc.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        tblBangDiem.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        tblBangDiem.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tblBangDiem);

        btnXemDiem.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnXemDiem.setText("Xem Điểm");
        btnXemDiem.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnXemDiem.setBorderPainted(false);
        btnXemDiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXemDiemActionPerformed(evt);
            }
        });

        cbblop.setBackground(new java.awt.Color(204, 204, 204));
        cbblop.setEditable(true);
        cbblop.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblDiemSV, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(lblMSSV, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtMSSV, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(lblHoTen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtHoTen, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(cbblop, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(lblMonHoc, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(cbbMonHoc, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(563, 563, 563))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(btnXemDiem, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(697, 697, 697))))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1575, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lblDiemSV, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblHoTen, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtHoTen, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtMSSV, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblMSSV, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                    .addComponent(cbblop))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblMonHoc, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbbMonHoc, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(btnXemDiem, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(77, 77, 77)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnXemDiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXemDiemActionPerformed
//        String monhoc = (String) cbbMonHoc.getSelectedItem();
//        boolean Tim = false;
//        List<ScheduledObjects> lstMonHoc = new ScheduledBLL().getElement(filename);
//        int size1 = lstMonHoc.size();
//        for (int i = 0; i < size1; i++) {
//            if (lstMonHoc.get(i).getTenMon().equals(monhoc)) {
//                String file = cbblop.getSelectedItem() + "-" + lstMonHoc.get(i).getMaMon() + ".csv";
//                List<StudyResultObjects> lstDiem = new StudyResultBLL().getElement(file);
//                int size = lstDiem.size();
//                for (int j = 0; j < size; j++) {
//                    if (lstDiem.get(j).getMSSV().equals(txtMSSV.getText())) {
//                        Tim = true;
//                        DefaultTableModel model = (DefaultTableModel) tblBangDiem.getModel();
//                        model.setRowCount(0);
//                        String[] columnsName = {"MSSV", "Họ Tên", "Điểm Giữa kỳ", "Điểm Cuối kỳ", "Điểm Khác", "Điểm Tổng Kết", "Kết Quả"};
//                        model.setColumnIdentifiers(columnsName);
//                        Vector row = new Vector();
//                        row.add(lstDiem.get(j).getMSSV());
//                        row.add(lstDiem.get(j).getHoten());
//                        row.add(lstDiem.get(j).getDiemGK());
//                        row.add(lstDiem.get(j).getDiemCK());
//                        row.add(lstDiem.get(j).getDiemKhac());
//                        float Diem = (lstDiem.get(j).getDiemGK() + lstDiem.get(j).getDiemCK() + lstDiem.get(j).getDiemKhac()) / 3;
//                        BigDecimal b = new BigDecimal(Diem);
//                        MathContext m = new MathContext(2);
//                        BigDecimal b1 = b.round(m);
//                        float DiemTong = b1.floatValue();
//                        row.add(DiemTong);
//                        String KQ;
//                        if (DiemTong < 5) {
//                            KQ = "Rớt";
//                        } else {
//                            KQ = "Đậu";
//                        }
//                        row.add(KQ);
//                        model.addRow(row);
//                    }
//                }
//            }
//        }
//        if(Tim == false)
//        {
//            JOptionPane.showMessageDialog(this, "Không tìm thấy mã số sinh viên " + username);
//        }
    }//GEN-LAST:event_btnXemDiemActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnXemDiem;
    private javax.swing.JComboBox<String> cbbMonHoc;
    private javax.swing.JComboBox<String> cbblop;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblDiemSV;
    private javax.swing.JLabel lblHoTen;
    private javax.swing.JLabel lblMSSV;
    private javax.swing.JLabel lblMonHoc;
    private javax.swing.JTable tblBangDiem;
    private javax.swing.JTextField txtHoTen;
    private javax.swing.JTextField txtMSSV;
    // End of variables declaration//GEN-END:variables
}
